baseURL = "https://froschdesign.github.io/documentation-status/"
languageCode = "en"
title = "Documentation Status - Laminas"
disableKinds = ["sitemap", "taxonomy", "RSS", "404", "taxonomyTerm"]
#sectionPagesMenu = "main"
#relativeURLs = true
#canonifyURLs = true

[markup]
    [markup.highlight]
        codeFences = false
    [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true

[menu]
  [[menu.main]]
    identifier = "components"
    name = "Components"
    weight = 10

  [[menu.main]]
    identifier = "components-documentation-listed"
    name = "Documentation Listed"
    url = "/components/documentation-listed"
    weight = 10
    parent = "components"

  [[menu.main]]
    identifier = "components-site-descriptions"
    name = "Site Descriptions"
    url = "/components/site-descriptions"
    weight = 20
    parent = "components"

  [[menu.main]]
    identifier = "components-installation-page"
    name = "Installation Page"
    url = "/components/installation-page"
    weight = 30
    parent = "components"

  [[menu.main]]
    identifier = "mezzio"
    name = "Mezzio"
    weight = 20

  [[menu.main]]
    identifier = "mezzio-documentation-listed"
    name = "Documentation Listed"
    url = "/mezzio/documentation-listed"
    weight = 10
    parent = "mezzio"

  [[menu.main]]
    identifier = "mezzio-site-descriptions"
    name = "Site Descriptions"
    url = "/mezzio/site-descriptions"
    weight = 20
    parent = "mezzio"

  [[menu.main]]
    identifier = "mezzio-installation-page"
    name = "Installation Page"
    url = "/mezzio/installation-page"
    weight = 30
    parent = "mezzio"